services:
  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: vpn_shop
      POSTGRES_USER: vpn_user
      POSTGRES_PASSWORD: vpn_pass
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - app_net

  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_net

  app:
    build: .
    restart: always
    expose:
      - "3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
    name: vpn_shop_net
